name: Integration test triggered on every push to main

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - '**.gitignore'
      - '**/images/**'
      - 'frontend/**'
      - 'azure/frontend-resources/**'
      - '.github/workflows/deploy-frontend.yml'

jobs:
  run_tests:
    runs-on: ubuntu-latest 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Python to support test environment
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'

      - name: Install test dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r azure/tests/requirements.txt
          python -m playwright install

      - name: Run integration test
        env:
          COSMOS_DB_ACCOUNT_NAME: ${{ vars.COSMOS_DB_ACCOUNT_NAME }}
          COSMOS_DB_TABLE_NAME: ${{ vars.COSMOS_DB_TABLE_NAME }}
          COSMOS_DB_PARTITION_KEY: ${{ vars.COSMOS_DB_PARTITION_KEY }}
          COSMOS_DB_ROW_KEY: ${{ vars.COSMOS_DB_ROW_KEY }}
          API_URL: ${{ vars.API_URL }}
        run: |
          pytest -q azure/tests/test_api.py
